image: php:7.2.8
pipelines:
  default:
    - step:
       script:
        - apt update && apt install git ssh -y
        - touch ~/.ssh/id_cdci_india_rsa.b64
        - chmod 600 ~/.ssh/id_cdci_india_rsa.b64
        - echo $CodeKey >> ~/.ssh/id_cdci_india_rsa.b64
        - cat ~/.ssh/id_cdci_india_rsa.b64|/usr/bin/base64 -d > ~/.ssh/id_cdci_india_rsa
        - chmod 400 ~/.ssh/id_cdci_india_rsa
        - echo $CodeConfig  > ~/.ssh/config.b64
        - cat ~/.ssh/config.b64 |/usr/bin/base64 -d > ~/.ssh/config
        - cat ~/.ssh/config
        - ssh paygo.in "cd /home/paygo/public_html/paygo && git checkout develop && eval \`ssh-agent\` && ssh-add ~/.ssh/id_cdci_india_rsa && git pull origin develop && exit"

